"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _reactNative = require("react-native");
// Generated by uniffi-bindgen-react-native
var _default = exports.default = _reactNative.TurboModuleRegistry.getEnforcing('BreezSdkSparkReactNative');
//# sourceMappingURL=NativeBreezSdkSparkReactNative.js.map